export const kanji = [	
  { key: '一', value: 'one'},
  { key: '二', value: 'two'},
  { key: '三', value: 'three'},
  { key: '四', value: 'four'},
  { key: '五', value: 'five'},
  { key: '六', value: 'six'},
  { key: '七', value: 'seven'},
  { key: '八', value: 'eight'},
  { key: '九', value: 'nine'},
  { key: '十', value: 'ten'},
  { key: '百', value: 'hundred'},
  { key: '千', value: 'thousand'},
  { key: '上', value: 'top, above'},
  { key: '下', value: 'bottom, below'},
  { key: '左', value: 'left'},
  { key: '右', value: 'right'},
  { key: '中', value: 'inside, middle'},
  { key: '大', value: 'large'},
  { key: '小', value: 'small'},
  { key: '月', value: 'month, moon'},
  { key: '日', value: 'day, sun'},
  { key: '年', value: 'year'},
  { key: '早', value: 'early'},
  { key: '木', value: 'tree'},
  { key: '林', value: 'woods'},
  { key: '山', value: 'mountain'},
  { key: '川', value: 'river'},
  { key: '土', value: 'soil'},
  { key: '空', value: 'sky'},
  { key: '田', value: 'rice field'},
  { key: '天', value: 'heaven, sky'},
  { key: '生', value: 'living, birth, raw'},
  { key: '花', value: 'flower'},
  { key: '草', value: 'grass'},
  { key: '虫', value: 'insect'},
  { key: '犬', value: 'dog'},
  { key: '人', value: 'person'},
  { key: '名', value: 'name'},
  { key: '女', value: 'female'},
  { key: '男', value: 'male'},
  { key: '子', value: 'child'},
  { key: '目', value: 'eye'},
  { key: '耳', value: 'ear'},
  { key: '口', value: 'mouth'},
  { key: '手', value: 'hand'},
  { key: '足', value: 'foot, suffice'},
  { key: '見', value: 'see'},
  { key: '音', value: 'sound'},
  { key: '力', value: 'power'},
  { key: '気', value: 'spirit, air'},
  { key: '円', value: 'yen, circle'},
  { key: '入', value: 'enter'},
  { key: '出', value: 'exit'},
  { key: '立', value: 'stand up'},
  { key: '休', value: 'rest'},
  { key: '先', value: 'previous'},
  { key: '夕', value: 'evening'},
  { key: '本', value: 'book'},
  { key: '文', value: 'text'},
  { key: '字', value: 'character'},
  { key: '学', value: 'study'},
  { key: '校', value: 'school'},
  { key: '村', value: 'village'},
  { key: '町', value: 'town'},
  { key: '森', value: 'forest'},
  { key: '正', value: 'correct'},
  { key: '水', value: 'water'},
  { key: '火', value: 'fire'},
  { key: '玉', value: 'jewel, ball'},
  { key: '王', value: 'king'},
  { key: '石', value: 'stone'},
  { key: '竹', value: 'bamboo'},
  { key: '糸', value: 'thread'},
  { key: '貝', value: 'shellfish'},
  { key: '車', value: 'vehicle'},
  { key: '金', value: 'gold, money'},
  { key: '雨', value: 'rain'},
  { key: '赤', value: 'red'},
  { key: '青', value: 'blue'},
  { key: '白', value: 'white'},
]