export const kanji = [	
  { key: '一', value: 'one', 'kunyomi': 'ひと-つ', 'onyomi': 'イチ'},
  { key: '二', value: 'two', 'kunyomi': 'ふた-つ', 'onyomi': 'ニ'},
  { key: '三', value: 'three', 'kunyomi': 'みっ-つ', 'onyomi': 'サン'},
  { key: '四', value: 'four', 'kunyomi': 'よっ-つ', 'onyomi': 'シ'},
  { key: '五', value: 'five', 'kunyomi': 'いつ-つ', 'onyomi': 'ゴ'},
  { key: '六', value: 'six', 'kunyomi': 'むっ-つ', 'onyomi': 'ロク'},
  { key: '七', value: 'seven', 'kunyomi': 'なな-つ', 'onyomi': 'シチ'},
  { key: '八', value: 'eight', 'kunyomi': 'やっ-つ', 'onyomi': 'ハチ'},
  { key: '九', value: 'nine', 'kunyomi': 'ここの-つ', 'onyomi': 'キュウ'},
  { key: '十', value: 'ten', 'kunyomi': 'とお', 'onyomi': 'ジュウ'},
  { key: '百', value: 'hundred', 'kunyomi': 'もも', 'onyomi': 'ヒャク'},
  { key: '千', value: 'thousand', 'kunyomi': 'ち', 'onyomi': 'セン'},
  { key: '上', value: 'top, above', 'kunyomi': 'うえ', 'onyomi': 'ジョウ'},
  { key: '下', value: 'bottom, below', 'kunyomi': 'した', 'onyomi': 'カ, ゲ'},
  { key: '左', value: 'left', 'kunyomi': 'ひだり', 'onyomi': 'サ'},
  { key: '右', value: 'right', 'kunyomi': 'みぎ', 'onyomi': 'ウ, ユウ'},
  { key: '中', value: 'inside, middle', 'kunyomi': 'なか', 'onyomi': 'チュウ'},
  { key: '大', value: 'large', 'kunyomi': 'おお', 'onyomi': 'ダイ, タイ'},
  { key: '小', value: 'small', 'kunyomi': 'ちい-さい', 'onyomi': 'ショウ'},
  { key: '月', value: 'month, moon', 'kunyomi': 'つき', 'onyomi': 'ゲツ, ガツ'},
  { key: '日', value: 'day, sun', 'kunyomi': 'ひ', 'onyomi': 'ニチ, ジツ'},
  { key: '年', value: 'year', 'kunyomi': 'とし', 'onyomi': 'ネン'},
  { key: '早', value: 'early', 'kunyomi': 'はや-い', 'onyomi': 'ソウ'},
  { key: '木', value: 'tree', 'kunyomi': 'き', 'onyomi': 'ボク, モク'},
  { key: '林', value: 'woods', 'kunyomi': 'はやし', 'onyomi': 'リン'},
  { key: '山', value: 'mountain', 'kunyomi': 'やま', 'onyomi': 'サン'},
  { key: '川', value: 'river', 'kunyomi': 'かわ', 'onyomi': 'セン'},
  { key: '土', value: 'soil', 'kunyomi': 'つち', 'onyomi': 'ド, ト'},
  { key: '空', value: 'sky', 'kunyomi': 'そら', 'onyomi': 'クウ'},
  { key: '田', value: 'rice field', 'kunyomi': 'た', 'onyomi': 'デン'},
  { key: '天', value: 'heaven, sky', 'kunyomi': 'あめ', 'onyomi': 'テン'},
  { key: '生', value: 'living, birth, raw', 'kunyomi': 'い-きる', 'onyomi': 'セイ, ショウ'},
  { key: '花', value: 'flower', 'kunyomi': 'はな', 'onyomi': 'カ'},
  { key: '草', value: 'grass', 'kunyomi': 'くさ', 'onyomi': 'ソウ'},
  { key: '虫', value: 'insect', 'kunyomi': 'むし', 'onyomi': 'チュウ'},
  { key: '犬', value: 'dog', 'kunyomi': 'いぬ', 'onyomi': 'ケン'},
  { key: '人', value: 'person', 'kunyomi': 'ひと', 'onyomi': 'ジン, ニン'},
  { key: '名', value: 'name', 'kunyomi': 'な', 'onyomi': 'メイ, ミョウ'},
  { key: '女', value: 'female', 'kunyomi': 'おんな', 'onyomi': 'ジョ, ニョ'},
  { key: '男', value: 'male', 'kunyomi': 'おとこ', 'onyomi': 'ダン, ナン'},
  { key: '子', value: 'child', 'kunyomi': 'こ', 'onyomi': 'シ'},
  { key: '目', value: 'eye', 'kunyomi': 'め', 'onyomi': 'モク, ボク'},
  { key: '耳', value: 'ear', 'kunyomi': 'みみ', 'onyomi': 'ジ'},
  { key: '口', value: 'mouth', 'kunyomi': 'くち', 'onyomi': 'コウ'},
  { key: '手', value: 'hand', 'kunyomi': 'て', 'onyomi': 'シュ'},
  { key: '足', value: 'foot, suffice', 'kunyomi': 'あし', 'onyomi': 'ソク'},
  { key: '見', value: 'see', 'kunyomi': 'み-る', 'onyomi': 'ケン'},
  { key: '音', value: 'sound', 'kunyomi': 'おと', 'onyomi': 'オン, イン'},
  { key: '力', value: 'power', 'kunyomi': 'ちから', 'onyomi': 'リョク, リキ'},
  { key: '気', value: 'spirit, air', 'kunyomi': 'き', 'onyomi': 'キ, ケ'},
  { key: '円', value: 'yen, circle', 'kunyomi': 'まる-い', 'onyomi': 'エン'},
  { key: '入', value: 'enter', 'kunyomi': 'はい-る', 'onyomi': 'ニュウ, ジュ'},
  { key: '出', value: 'exit', 'kunyomi': 'で-る', 'onyomi': 'シュツ, スイ'},
  { key: '立', value: 'stand up', 'kunyomi': 'た-つ', 'onyomi': 'リツ'},
  { key: '休', value: 'rest', 'kunyomi': 'やす-む', 'onyomi': 'キュウ'},
  { key: '先', value: 'previous', 'kunyomi': 'さき', 'onyomi': 'セン'},
  { key: '夕', value: 'evening', 'kunyomi': 'ゆう', 'onyomi': 'セキ'},
  { key: '本', value: 'book', 'kunyomi': 'もと', 'onyomi': 'ホン'},
  { key: '文', value: 'text', 'kunyomi': 'ふみ', 'onyomi': 'ブン, モン'},
  { key: '字', value: 'character', 'kunyomi': 'あざ', 'onyomi': 'ジ'},
  { key: '学', value: 'study', 'kunyomi': 'まな-ぶ', 'onyomi': 'ガク'},
  { key: '校', value: 'school', 'kunyomi': 'こう', 'onyomi': 'コウ'},
  { key: '村', value: 'village', 'kunyomi': 'むら', 'onyomi': 'ソン'},
  { key: '町', value: 'town', 'kunyomi': 'まち', 'onyomi': 'チョウ'},
  { key: '森', value: 'forest', 'kunyomi': 'もり', 'onyomi': 'シン'},
  { key: '正', value: 'correct', 'kunyomi': 'ただ-しい', 'onyomi': 'セイ, ショウ'},
  { key: '水', value: 'water', 'kunyomi': 'みず', 'onyomi': 'スイ'},
  { key: '火', value: 'fire', 'kunyomi': 'ひ', 'onyomi': 'カ'},
  { key: '玉', value: 'jewel, ball', 'kunyomi': 'たま', 'onyomi': 'ギョク'},
  { key: '王', value: 'king', 'kunyomi': 'おう', 'onyomi': 'オウ'},
  { key: '石', value: 'stone', 'kunyomi': 'いし', 'onyomi': 'セキ'},
  { key: '竹', value: 'bamboo', 'kunyomi': 'たけ', 'onyomi': 'チク'},
  { key: '糸', value: 'thread', 'kunyomi': 'いと', 'onyomi': 'シ'},
  { key: '貝', value: 'shellfish', 'kunyomi': 'かい', 'onyomi': 'バイ'},
  { key: '車', value: 'vehicle', 'kunyomi': 'くるま', 'onyomi': 'シャ'},
  { key: '金', value: 'gold, money', 'kunyomi': 'かね', 'onyomi': 'キン, コン'},
  { key: '雨', value: 'rain', 'kunyomi': 'あめ', 'onyomi': 'ウ'},
  { key: '赤', value: 'red', 'kunyomi': 'あか', 'onyomi': 'セキ'},
  { key: '青', value: 'blue', 'kunyomi': 'あお', 'onyomi': 'セイ, ショウ'},
  { key: '白', value: 'white', 'kunyomi': 'しろ', 'onyomi': 'ハク'},
]