export const kanji = [	
  { key: '一', value: 'one' },
  { key: '二', value: 'two' },
  { key: '三', value: 'three' },
  { key: '四', value: 'four' },
  { key: '五', value: 'five' },
  { key: '六', value: 'six' },
  { key: '七', value: 'seven' },
  { key: '八', value: 'eight' },
  { key: '九', value: 'nine' },
  { key: '十', value: 'ten' },
  { key: '百', value: 'hundred' },
  { key: '千', value: 'thousand' },
  { key: '万', value: 'ten thousand' },
  { key: '円', value: 'yen' },
  { key: '日', value: 'day' },
  { key: '本', value: 'book' },
  { key: '人', value: 'person' },
  { key: '月', value: 'moon' },
  { key: '火', value: 'fire' },
  { key: '水', value: 'water' },
  { key: '木', value: 'tree' },
  { key: '金', value: 'gold' },
  { key: '土', value: 'earth' },
  { key: '曜', value: 'day of the week' },
  { key: '年', value: 'year' },
  { key: '時', value: 'time' },
  { key: '分', value: 'minute' },
  { key: '半', value: 'half' },
  { key: '今', value: 'now' },
  { key: '前', value: 'before' },
  { key: '後', value: 'after' },
  { key: '来', value: 'come' },
  { key: '行', value: 'go' },
  { key: '食', value: 'eat' },
  { key: '飲', value: 'drink' },
  { key: '見', value: 'see' },
  { key: '聞', value: 'hear' },
  { key: '話', value: 'talk' },
  { key: '読', value: 'read' },
  { key: '書', value: 'write' },
  { key: '学', value: 'learn' },
  { key: '知', value: 'know' },
]