export const words = ['abodes', 'acrid', 'actually', 'adaptable', 'adds', 'adjusted', 'adorable', 'aggravate', 'Alberta', 
    'Alhambra', 'alternate', 'ambient', 'Andalusian', 'Andean', 'andromeda', 'Angola', 'another', 'antidote', 'apartment', 
    'apex', 'appendages', 'archers', 'architrave', 'Arcturus', 'area', 'arrested', 'arrive', 'arrows', 'assimilation', 
    'astride', 'athenaeum/atheneum', 'awesome', 'aye-aye', 'Ayurvedic', 'Azores', 'baggy', 'balance', 'ballast', 'balm', 
    'bandage', 'bandmates', 'Bangalore', 'barked', 'batten', 'beetle', 'beginning', 'Beijing', 'belongs', 
    'benefited/benefitted', 'benighted', 'beyond', 'bill', 'biryani/biriani', 'blame', 'blasphemous', 'blast', 
    'blessings', 'blotch', 'blue', 'bobbed', 'bones', 'bossiness', 'bottom', 'bovines', 'broached', 'brooding', 'bruise', 
    'build', 'busy', 'came', 'camel', 'Camelot', 'can', 'canid', 'caparisoned', 'carillon', 'casa', 'catastrophe', 
    'ceiling', 'chachalacas', 'chase', 'chatelaine', 'chemotherapy', 'chiasmus', 'Chicago', 'choose', 'chores', 'chunks', 
    'churned', 'cirque', 'cirrhosis', 'clash', 'clerisy', 'color/colour', 'comic', 'commemoration', 'compute', 
    'configuration', 'confiscated', 'conifers', 'conjugate', 'constant', 'container', 'contours', 'coop', 'copy', 
    'cortege', 'cottonwood', 'counterfeit', 'crafty', 'crevices', 'cronies', 'crops', 'cry', 'cuirass', 'cul-de-sac', 
    'cups', 'curly', 'cute', 'dais', 'damaged', 'debit', 'decide', 'declaration', 'defunct', 'deign', 'deviation', 
    'devoured', 'disband', 'discarded', 'display', 'dissolute', 'distracted', 'doll', 'donkeys', 'doodled', 'doorjamb', 
    'doppelgänger', 'drag', 'dredged', 'during', 'ears', 'easily', 'ebb', 'economy', 'efficient', 'effigy', 'elves', 
    'embossed', 'embrace', 'emigrate', 'enamel', 'encompass', 'equipment', 'estampies', 'eurhythmics/eurythmics', 
    'evaded', 'everlasting', 'everyone', 'exciting', 'exhilaration', 'fado', 'faith', 'fasting', 'feedback', 'feel', 
    'feisty', 'few', 'files', 'five', 'floral', 'flybys', 'food', 'forget', 'former', 'forsooth', 'foster', 'frantic', 
    'freedom', 'fudge', 'fumatorium', 'funky', 'Gaels', 'garderobe', 'geopolitics', 'glide', 'gloomy', 'grass', 'gravy', 
    'greasy', 'greeting', 'grimy', 'growling', 'had', 'harsh', 'hauling', 'heavy', 'help', 'hematology', 'hey', 'hint', 
    'hitched', 'hobbledehoy', 'homeopathic', 'hot', 'humbug', 'hummingbird', 'hurdy-gurdy', 'impudence', 'inaudible', 
    'incontrovertible', 'infrared', 'inkling', 'inlet', 'innings', 'innocent', 'instead', 'interesting', 'intertribal', 
    'intubated', 'Jicarilla', 'jinx', 'joggled', 'kirpan', 'kneeling', 'kumkum', 'landline', 'Leander', 'leave', 'like', 
    'limbering', 'Lithuania', 'long', 'look', 'lousy', 'lurid', 'lustrum', 'make', 'maneuverable', 'Manhattan', 
    'maniacal', 'many', 'map', 'marguerite', 'marry', 'masa', 'mausoleum', 'meal', 'menacing', 'mercenary', 'minerals', 
    'minute', 'miscellaneous', 'misericordes/misericords', 'model', 'moo', 'moon', 'mullioned', 'murals', 'mutiny', 
    'nares', 'Navajo/Navaho', 'need', 'nets', 'newt', 'nimble', 'nobody', 'nom de plume', 'none', 'nose', 'not', 
    'observations', 'off', 'offhandedly', 'oftentimes', 'Ohio', 'oncologist', 'only', 'orca', 'ordained', 'order', 
    'overseas', 'overtly', 'pace', 'page', 'pail', 'pandemic', 'pangs', 'pants', 'paradise', 'parathas', 'party', 
    'peacock', 'peevish', 'pell-mell', 'Penelope', 'people', 'philology', 'phone', 'pioneered', 'Piraeus', 'pistons', 
    'pitch-black', 'plan', 'pneumonia', 'pod', 'poke', 'pomade', 'poppet', 'porch', 'potential', 'potion', 'pottery', 
    'preternaturally', 'probably', 'prophetically', 'proscribed', 'provocation', 'purchase', 'put', 'puttering', 
    'python', 'quiet', 'railings', 'rare', 'reenactment', 'rejoinder', 'rental', 'republic', 'reservation', 'respond', 
    'retribution', 'rice', 'riffled', 'rituals', 'roots', 'roulette', 'ruckus', 'sackbuts', 'saints', 'saltarellos', 
    'Sanskrit', 'scared', 'scars', 'scrawled', 'section', 'sedan', 'seminary', 'serum', 'share', 'shawl', 'sheepish', 
    'sheesh', 'shelf', 'shrivel', 'sifting', 'sights', 'Sikhism', 'sink', 'sit', 'skidded', 'skipped', 'slather', 
    'slippery', 'slivers', 'slouch', 'smell', 'smirk', 'smite', 'smooshed', 'snooty', 'sockets', 'soldiers', 'sole', 
    'some', 'sorry', 'spading', 'Spandau', 'sparrow', 'speck', 'spellbound', 'spic-and-span/spick-and-span', 'squinched', 
    'stairs', 'starboard', 'stinky', 'story', 'streak', 'stumped', 'stuttered', 'subservient', 'subsidence', 'sway', 
    'swept', 'switcheroo', 'swoop', 'table', 'tales', 'tallyho', 'Tamil', 'tankard', 'telenovelas', 'tell', 
    'temperature', 'ten', 'tenets', 'thurible', 'tiara', 'tilapia', 'tingle', 'tiny', 'tomorrow', 'top', 'torment', 
    'tote', 'tower', 'toys', 'traditional', 'trap', 'trash', 'trees', 'trey', 'trilby', 'trout', 'twelve', 'two', 
    'unacknowledged', 'undine', 'until', 'upbeat', 'uplift', 'urad', 'urchins', 'vertical', 'vestments', 'Vesuvian', 
    'visit', 'waist', 'washing', 'weave', 'what', 'white', 'whizzed', 'Wi-Fi', 'wiggle', 'wonder', 'wrestle', 'xylem', 
    'yurt', 'Zimbabwe'];