export const words = ['able', 'acclimate', 'aerosol', 'Afrobeat', 'again', 'ailment', 'Albuquerque', 'altimeter', 'ambush', 'amphitheater', 'amphoras', 'amused', 'angry', 'animatronics', 'antechamber',
 'antimony', 'antlers', 'antonyms', 'anybody', 'appreciation', 'April', 'aptitude', 'Arabic', 'arable', 'Arctic', 'aspirin', 'Assam', 'attorney', 'aura', 'avens', 'awfully', 'back', 'bamboozled', 
 'barely', 'bedroom', 'bestie', 'bike', 'bilge', 'bionic', 'blank', 'block', 'boba', 'bow', 'brain', 'branch', 'brave', 'bride', 'bright', 'broken', 'bronze', 'Brooklyn', 'buckeye', 'bunions',
 'Bunsen burner', 'bureaucrats', 'bursting', 'captain', 'categorically', 'centrifuge', 'cereal', 'chasm', 'Chicana', 'chin', 'clearly', 'climb', 'cloth', 'cluttered', 'coat', 'coccidiosis', 'coleus',
 'combat', 'commandments', 'communing', 'completely', 'composition', 'conciliatory', 'confident', 'congregation', 'conjunto', 'contagion', 'contemptible', 'cool', 'Copenhagen', 'corner', 'craquelure',
 'create', 'credit', 'cress', 'crookedly', 'crown', 'dance', 'dapper', 'dazzle', 'deadpan', 'deal', 'dear', 'decibels', 'deficiencies', 'defoliant', 'delegation', 'deliberately', 'demure',
 'dendrochronology', 'desecration', 'dessert', 'destitution', 'devotion', 'diamond', 'dilute', 'diode', 'disclaimer', 'disdain', 'disgruntled', 'divot', 'doctor', 'dots', 'doughnut / donut', 'drawers',
 'drawl', 'drew', 'droll', 'drooped', 'dynasty', 'edge', 'ellipsis', 'elongated', 'endless', 'engulf', 'enter', 'Erlenmeyer flask', 'evening', 'expressway', 'expulsion', 'extravagant', 'fallow',
 'fascinated', 'fens', 'fiddlehead', 'finally', 'find', 'fireworks', 'first', 'flea', 'flitting', 'float', 'flowers', 'fluke', 'flummox / flummix / flummux', 'forearms', 'forsook', 'four', 'fowl',
 'fragrant', 'frijoles', 'front', 'furniture', 'fury', 'gallon', 'gastritis', 'gather', 'gazed', 'gently', 'Gilgamesh', 'give', 'glasses', 'glittery', 'gloaming', 'glue', 'glumly', 'gorilla', 'graduate',
 'grand', 'gratitude', 'grebe', 'grid', 'gross', 'ground', 'hair', 'hard', 'havens', 'haw', 'heap', 'his', 'hitherto', 'hobbit', 'horticulture', 'howdy', 'hug', 'hungrily', 'hypocaust', 'ignore',
 'Illinois', 'important', 'improve', 'incandescent', 'incarnated', 'incense', 'incited', 'incubator', 'indignant', 'information', 'innards', 'inscription', 'inscrutable', 'insolent', 'insufferable',
 'insulation', 'insult', 'Internet', 'interstellar', 'intertwine', 'intimidate', 'inventory', 'invisible', 'jeopardy', 'join', 'jugular', 'koi', 'kung fu', 'ladder', 'lanthanides', 'lasso / lassoo',
 'later', 'Laundromat', 'leks', 'letter', 'little', 'live', 'luciferin', 'lymphoma', 'Macao / Macau', 'Macedonia', 'magistrates', 'malicious', 'malignant', 'malnutrition', 'mangels', 'mantel / mantle',
 'manual', 'marble', 'matterhorn', 'May', 'megaron', 'meitnerium', 'metronome', 'mile', 'minimus', 'mischievous', 'moira', 'more', 'mother', 'mound', 'Mumbai', 'music', 'nagged', 'name', 'near', 'nest',
 'nighttime', 'nitrogen', 'nondescript', 'nopales', 'notebook', 'occupy', 'oddity', 'Okefenokee', 'Oman', 'oops', 'open', 'other', 'ourselves', 'outfits', 'overcome', 'palomino / palamino', 'pantry',
 'paralysis', 'park', 'pat', 'patronize / patronise', 'peaceful', 'peel', 'peplos / peplus', 'perpendicularity', 'pervading', 'petticoat', 'pews', 'photosynthesis', 'pinyin', 'pipette / pipet',
 'pixels', 'platypus', 'plaza', 'Pleiades', 'plunger', 'point', 'poisonous', 'pole', 'Popocatepetl', 'popovers', 'possible', 'pouch', 'pour', 'practice / practise', 'precious', 'present', 'pride',
 'privilege', 'pronaos', 'propitious', 'provision', 'pullets', 'punctually', 'putty', 'quarry', 'quip', 'quotation', 'Ramadan / Ramadhan', 'razor', 'really', 'recede', 'recital', 'reference', 'refuge',
 'reindeer', 'replace', 'replica', 'repose', 'responsible', 'retinitis pigmentosa', 'river', 'roads', 'roast', 'rooibos tea', 'rotten', 'roughly', 'rude', 'rug', 'sacred', 'salute', 'Samian', 'saucer',
 'sauna', 'sausage', 'scan', 'scandium', 'scream', 'second', 'secreted', 'senescent', 'sentinel', 'serenity', 'sewing', 'Shaanxi', 'shall', 'shoal', 'shower', 'shutters', 'silence', 'silicon',
 'simultaneously', 'sips', 'sketch', 'sky', 'slakes', 'smaller', 'snack', 'snail', 'snake', 'snap', 'snivel', 'societal', 'solve', 'spacious', 'spark', 'spawned', 'sphagnum', 'spoon', 'spring',
 'sprocket', 'squash', 'squire', 'stagecoach', 'stall', 'state', 'steeds', 'steel', 'stew', 'stitchery', 'stood', 'store', 'stove', 'stroll', 'submerged', 'subway', 'sudsy', 'sultanate', 'Sumerian',
 'superior', 'surfactant', 'syllables', 'Taoism / Daoism', 'tape', 'termite', 'terrify', 'Tetrazzini', 'this', 'thorax', 'thoughts', 'thousand', 'thumbs', 'Thursday', 'thyroid', 'tide', 'together',
 'toss', 'tostones', 'transform', 'Trinidadian', 'tripe', 'tubes', 'tug', 'tune', 'tunic', 'turban', 'turquoise / turquois', 'uncanny', 'valley', 'vase', 'Vaseline', 'Versailles', 'verve', 'vision',
 'voracious', 'vultures', 'wafting', 'wag', 'wake', 'wears', 'wedding', 'wheezy', 'while', 'whisper', 'why', 'wisdom', 'wish', 'wok', 'worth', 'wow', 'yesterday', 'zip'];
 